<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kotlin.java</groupId>
    <artifactId>kotlinjava</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.13</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <java.version>26</java.version>
        <kotlin.version>2.3.10</kotlin.version>
        <kotlinx.serialization.json.version>1.10.0</kotlinx.serialization.json.version>
        <kotlinx.coroutines.version>1.10.2</kotlinx.coroutines.version>
        <kotlin.bom>2.3.10</kotlin.bom>
        <kotlinx.datetime.jvm.version>0.7.1</kotlinx.datetime.jvm.version>
        <maven.assembly.plugin.version>3.8.0</maven.assembly.plugin.version>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>

        <!-- Enable incremental compilation﻿-->
        <!-- To make your builds faster, you can enable incremental compilation by adding the kotlin.compiler.incremental property-->
        <!-- https://kotlinlang.org/docs/maven-compile-package.html#specify-compiler-options-->
        <kotlin.compiler.incremental>true</kotlin.compiler.incremental>
        <kotlin.compiler.languageVersion>2.3</kotlin.compiler.languageVersion>

        <spring-boot.version>3.5.13</spring-boot.version>
    </properties>

    <dependencies>
        <!-- kotlin begin -->
        <!-- Dependency on the standard library-->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <!-- Uses the kotlin.version property
                specified in <properties/>: -->
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json</artifactId>
            <version>${kotlinx.serialization.json.version}</version>
        </dependency>
    <!--Dependencies on test libraries Kotlin-->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <scope>test</scope>
        </dependency>
    <!--Dependency on a kotlinx library﻿-->
    <!--For kotlinx libraries, you can either add the base artifact name or the name with a -jvm suffix.
     Refer to the library's README file on https://klibs.io/?_gl=1*1mpg55d*_gcl_au*NzAzMzYxOTc4LjE3NzM2NDIwMzQ.*_ga*MTkxNDY0OTY5LjE3NzM2NDIwMzQ.*_ga_9J976DJZ68*czE3NzM2NDYwODEkbzIkZzAkdDE3NzM2NDYwODEkajYwJGwwJGgw.-->
    <!--        Dependency on kotlinx.coroutines library-->
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>${kotlinx.coroutines.version}</version>
        </dependency>
        <!-- Dependency on the kotlinx-datetime library-->
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-datetime-jvm</artifactId>
            <version>${kotlinx.datetime.jvm.version}</version>
        </dependency>
        <!-- kotlin end -->

        <!-- spring boot begin-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- spring boot end-->

        <!-- Other -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
            <scope>provided</scope>
        </dependency>
        <!-- Other End -->
    </dependencies>

    <!-- Kotlin Bill of Materials (BOM), add a dependency on kotlin-bom-->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-bom</artifactId>
                <version>${kotlin.bom}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <!-- Compile and package a Maven project-->
        <!-- Configure source code compilation-->
        <!-- Compile Kotlin and Java sources https://kotlinlang.org/docs/maven-compile-package.html#compile-kotlin-and-java-sources -->
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <executable>false</executable>
                    <excludeDevtools>true</excludeDevtools>
                    <mainClass>com.kotlin.java.KotlinJavaApplication</mainClass>
                </configuration>
            </plugin>
            <!-- Kotlin compiler plugin configuration -->
            <!-- Данная конфигурация гарантирует, что:-->
            <!-- Сначала компилируется код на Kotlin.-->
            <!-- Код Java компилируется после Kotlin и может ссылаться на классы Kotlin.-->
            <!-- Стандартное поведение Maven не изменяет порядок плагинов.-->
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <!-- Ensure Kotlin code can reference Java code -->
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-test-compile</id>
                        <phase>test-compile</phase>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <!-- Ensure Kotlin code can reference Java code -->
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- No need to configure Maven compiler plugin with extensions -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>java-compile</id>
                        <phase>compile</phase>
                        <goals> <goal>compile</goal> </goals>
                    </execution>
                    <execution>
                        <id>java-test-compile</id>
                        <phase>test-compile</phase>
                        <goals> <goal>testCompile</goal> </goals>
                    </execution>
                </executions>
            </plugin>

        <!-- Create self-contained JAR files-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${maven.assembly.plugin.version}</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals> <goal>single</goal> </goals>
                        <configuration>
                            <archive>
                                <manifest>
                                    <mainClass>${main.class}</mainClass>
                                </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spring-repo</id>
            <url>https://repo.spring.io/release</url>
        </repository>
    </repositories>

</project>